POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Node video",
    "description": "This is the video 01",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/dbd21f30-b258-4bdd-977d-4f1952e1d010
Content-type: application/json

{
    "title": "Video 02",
    "description": "This is the video 01",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/b5963e98-65fb-423b-bc5b-0a45b990ce5a